create table public.profiles (
  id bigint generated by default as identity primary key,
  email text not null,
  first_name text
);

create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, first_name)
  values (
      new.id, 
      new.email, 
      new.raw_user_meta_data ->> 'first_name'
  );
  return new;
end;
$$ language plpgsql security definer;


create table public.book_library (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  g_id text not null,
  title text,
  authors text,
  thumbnail text,
  categories text,
  rating float,
  insertedAt timestamp with time zone default timezone('utc'::text, now()) not null
);

create table public.book_wishlist (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  g_id text not null,
  title text,
  authors text,
  thumbnail text,
  categories text,
  rating float,
  insertedAt timestamp with time zone default timezone('utc'::text, now()) not null
);